### PR TITLE
private __clone function is added

### PR DESCRIPTION
**Pull request by saimonh3**

### CODE REVIEW

**Comment by sohelamin** [comment]
Describe a little bit what does __clone() method? and what is the impact of __clone() in a singleton pattern?

**Comment by saimonh3** [comment]
The __clone() method is used to deep copy of an object and declaring the __clone() as a private method will prevent the object to be cloned using the clone keyword.

**Comment by sohelamin** [comment]
@saimonh3 I didn't mean to describe it here.

**Comment by sohelamin** [comment]
@saimonh3 Here is the commit 915026e34c what I want from you.
For now, I'm closing your PR. Please feel free to contribute to howtocode with a nice explanation :)

**Pull request closed without merging**
